## Starting Emotion Analysis

In [2]:
import numpy as np
import pandas as pd

import string

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('../data/train.txt', sep=';', header=None, names=['text','emotion'])

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [5]:
df.isna().sum()

text       0
emotion    0
dtype: int64

In [6]:
unique_emotions = df['emotion'].unique()
emotion_numbers ={}
i=0
for emo in unique_emotions:
    emotion_numbers[emo]=i
    i=i+1
df['emotion']=df['emotion'].map(emotion_numbers)

In [7]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [8]:
df['text']=df['text'].apply(lambda x: x.lower())

In [9]:
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [10]:
df['text']=df['text'].apply(remove_punc)

In [11]:
def remove_number(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new +i
    return new

df['text']=df['text'].apply(remove_number)

In [12]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new = new + i
    return new

df['text']=df['text'].apply(remove_emojis)

In [13]:
nltk.download('punkt')
nltk.download('stopwords')

/run/media/biplob/e1a9a613-7e49-4b9e-81ed-a1c7ad2b4cae/biplob/Emotion_analysis/jupyter-venv/lib/python3.14/site-packages/nltk/downloader.py:1076: UserWarning: NLTK will not authorize the non-private download directory '/home/biplob/nltk_data': it (or an ancestor) is world- or group-writable, so another local user could plant files there. Choose a private location such as ~/nltk_data.
  for msg in self.incr_download(info_or_id, download_dir, force):
[nltk_data] Downloading package punkt to /home/biplob/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/biplob/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [14]:
stop_words = set(stopwords.words('english'))

In [15]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [16]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [17]:
def remove_func(txt):
    words = word_tokenize(txt)
    cleaned_text=[]
    for i in words:
        if not i in stop_words:
            cleaned_text.append(i)
    return " ".join(cleaned_text)

df['text']=df['text'].apply(remove_func)

In [18]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

# Train Test Split

In [19]:
X= df['text']
y=df['emotion']

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Vectorization

In [21]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

# Bag of Words (BoW)

In [22]:
bow_vect = CountVectorizer()

In [23]:
X_train_bow = bow_vect.fit_transform(X_train)
X_test_bow=bow_vect.transform(X_test)

In [24]:
X_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116049 stored elements and shape (12800, 13359)>

In [25]:
X_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26934 stored elements and shape (3200, 13359)>

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [28]:
nb_pred= nb_model.predict(X_test_bow)

In [29]:
print(accuracy_score(y_test,nb_pred))

0.7678125

# TF-IDF

In [30]:
tfidf_vect = TfidfVectorizer()

In [31]:
X_train_tf=tfidf_vect.fit_transform(X_train)
X_test_tf=tfidf_vect.transform(X_test)

In [32]:
nb2_model = MultinomialNB()
nb2_model.fit(X_train_tf,y_train)

MultinomialNB()

In [33]:
tf_pred = nb2_model.predict(X_test_tf)
print(accuracy_score(y_test,tf_pred))

0.6609375

# Using Logistic Regression

In [34]:
lg_model = LogisticRegression(max_iter=1000)
lg_model.fit(X_train_tf,y_train)

LogisticRegression(max_iter=1000)

In [35]:
lg_pred = lg_model.predict(X_test_tf)
print(accuracy_score(y_test,lg_pred))

0.8615625

# Support Vector Machine (SVM)

In [36]:
from sklearn.svm import SVC

In [38]:
svm_model = SVC()
svm_model.fit(X_train_tf,y_train)

SVC()

In [39]:
svm_pred = svm_model.predict(X_test_tf)

In [48]:
print("Accuracy of Support Vector Machine using tf-idf is:",accuracy_score(y_test,svm_pred))

Accuracy of Support Vector Machine using tf-idf is: 0.8515625

In [42]:
svm2_model = SVC()
svm2_model.fit(X_train_bow,y_train)

SVC()

In [43]:
svm2_pred = svm2_model.predict(X_test_bow)

In [49]:
print("Accuracy of SVM using BoW is:",accuracy_score(y_test,svm2_pred))

Accuracy of SVM using BoW is: 0.8225

# Random Forest

In [45]:
from sklearn.ensemble import RandomForestClassifier

In [46]:
rf_model=RandomForestClassifier()

In [47]:
rf_model.fit(X_train_bow,y_train)

RandomForestClassifier()

In [53]:
rf_pred = rf_model.predict(X_test_bow)
print("Accuracy of random forest using (BoW) is:",accuracy_score(y_test,rf_pred))

Accuracy of random forest using (BoW) is: 0.8846875

In [54]:
rf2_model = RandomForestClassifier()
rf2_model.fit(X_train_tf,y_train)

RandomForestClassifier()

In [55]:
rf2_pred = rf2_model.predict(X_test_tf)

In [56]:
print("Accuracy of Random Forest using(tf-idf) is:",accuracy_score(y_test,rf2_pred))

Accuracy of Random Forest using(tf-idf) is: 0.8796875